# SPDX-License-Identifier: Apache-2.0
# Copyright 2023 Canonical Ltd.
# Copyright 2024 Intel Corporation

name: CDAC Push Image Workflow

on:
  workflow_dispatch:

jobs:
  docker-build-push-images:
    runs-on: ubuntu-latest

    env:
      REGISTRY: docker.io
      DOCKER_REGISTRY: docker.io/
      DOCKER_REPOSITORY: cdac5gc/
      
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - run: echo GIT_SHA_SHORT=$(git rev-parse --short HEAD) >> $GITHUB_ENV

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        env:
          DOCKER_TAG: master-latest
        run: |
            make docker-build

      - name: Tag Docker image latest
        run: |
          docker tag 5gc-pcf:master-latest ${{ env.DOCKER_REPOSITORY }}pcf:master-latest

      - name: Push Docker image latest to Docker Hub
        run: |
          docker push ${{ env.DOCKER_REPOSITORY }}pcf:master-latest

      - name: Tag Docker image "master-GIT_SHA"
        run: |
          docker tag 5gc-pcf:0.0.1-dev ${{ env.DOCKER_REPOSITORY }}pcf:master-${{ env.GIT_SHA_SHORT }}

      - name: Push Docker image "master-GIT_SHA" to Docker Hub
        run: |
          docker push ${{ env.DOCKER_REPOSITORY }}pcf:master-${{ env.GIT_SHA_SHORT }}