# SPDX-License-Identifier: Apache-2.0
# Copyright 2023 Canonical Ltd.
# Copyright 2024 Intel Corporation

name: Release Push Image Workflow

on:
  workflow_dispatch:

jobs:
  docker-build-push-images:
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      DOCKER_REGISTRY: ghcr.io/
      DOCKER_REPOSITORY: ios-mcn-core/
      RELEASE_VERSION: 0.0.2
      
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - run: echo GIT_SHA_SHORT=$(git rev-parse --short HEAD) >> $GITHUB_ENV

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.GHCRUSER }}
          password: ${{ secrets.GHCRPASS }}
      - name: Clean Checksum
        run: go mod tidy
      - name: Build Docker image
        env:
          DOCKER_TAG: release-${{ env.RELEASE_VERSION }}
        run: |
            make docker-build
            
      - name: Tag Docker image latest
        run: |
          docker tag ${{ env.DOCKER_REGISTRY}}${{ env.DOCKER_REPOSITORY}}5gc-amf:release-${{ env.RELEASE_VERSION }} ${{ env.DOCKER_REPOSITORY }}5gc-amf:release-${{ env.RELEASE_VERSION }}

      - name: Push Docker image latest to Github
        run: |
          make docker-push ${{ env.DOCKER_REPOSITORY }}5gc-amf:release-${{ env.RELEASE_VERSION }}
